### ISSUE TITLE
Go to the dashboard or main page directly when I enter in the URL in the browser

### ISSUE THREAD

**Issue by DatNgoNYC** [DatNgoNYC/anythingyouwantt#1]
### User Story
As an existing customer I want to be to go to the dashboard or main page directly when I enter in the URL in the browser so that I can quickly access my orders if I really want to check out the things I've wanted... plus other pages...

**Functional Requirements**
- [ ] Going to anythingyouwantt.com takes me to the main page 
- [ ] going to /dashboard/whatyouwanted should take me to all things i've wanted
- [ ] going to other pages are other important as well, flexibility here to create routing depending on its difficulty and time left.

**Non-Functional Requirements**
_some non-functional requirements to take note of as we design the solution to the user story_
- [ ] Should be fast load time (first contentful paint) no matter the route accessed.

### Task List
- [ ] Enable routing with dynamic importing in react app
