### ISSUE TITLE
I want to be able to search for anything i want and then order it

### ISSUE THREAD

**Issue by DatNgoNYC** [DatNgoNYC/anythingyouwantt#3]
### User Story
As an existing customer I want to be able to go look for anything i want and then order it so that "i can get anything i want"

**User Acceptance Criteria**
- [ ]  When I'm on the home page I can enter in the thing I want
- [ ]  I can then "check it out"
- [ ]  There should be a confirmation popup/feedback to know i've successfully ordered it.
- [ ] "get anything i want" will come in the form of an email receipt of the thing! 
- [ ] The email should show "everything" about the order

**Non-Functional Requirements**
some non-functional requirements to take note of as we design the solution to the user story
- [ ] None we can think of rn

**Task List**
- [ ] Take the order input and create an "order" in the database
- [ ] Get the image from Unsplash API, one for preview and one fullsize,
- [ ] store it in s3, RDS won't be able to handle to image size so create an image model with a reference to s3identifier?
- [ ] In transit, after succesffuly storing, send an email to the user with the image and title,order date, delivery timeline?, etc.
