### ISSUE TITLE
I want to be able to signup/signin with google

### ISSUE THREAD

**Issue by DatNgoNYC** [DatNgoNYC/anythingyouwantt#4]
### User Story
As a potential customer I want to be able to signup/signin with google so that i know my account was made with a brand I trust (google)

**User Acceptance Criteria**
- [ ] If I wasn't logged in before (ie new user to the site), then when I go to the main page i have the option of signing up.
- [ ] When i press signup I want to be able to sign up with google the way i do for other websites i use google login
- [ ] I want to see my name and email in the accounting settings and my google profile image so that i know google login worked successfully.
- [ ] I can sign out once I am signed in.
- [ ] If i refresh the page I will stay signed in

**Non-Functional Requirements**
some non-functional requirements to take note of as we design the solution to the user story
- [ ] The user should stay signed in if it's like their personal computer or that sort. 

**Task List**
- [ ] Look into passportjs and the google-oauth20 strategy. 
- [ ] Build the database based on the type of information we can get from Google
