### ISSUE TITLE
I want to be able to stay signed in when i refresh or reopen the website

### ISSUE THREAD

**Issue by DatNgoNYC** [DatNgoNYC/anythingyouwantt#5]
### User Story
As an existing user I want to be able to stay signed in when i refresh or reopen the website.

**User Acceptance Criteria**
- [ ] When I refresh the site i am still logged in. 
- [ ] when i go to the website after having recently used it i stay logged in.
- [ ] i understand there's a very abstract time element to how long a user stays logged in so just go with what is most sensical.

**Non-Functional Requirements**
some non-functional requirements to take note of as we design the solution to the user story
- [ ] maybe something with only staying logged in if it's a trusted computer? not a priority.

**Task List**
- [ ] Look into passportjs's session management. 
- [ ] Build the database based on the type of information we can get from the profile object
