### ISSUE TITLE
As a customer who's place orders before, I want to be able to see all the orders that I've placed before so that I can check it out again

### ISSUE THREAD

**Issue by DatNgoNYC** [DatNgoNYC/anythingyouwantt#6]
### User Story
As a customer who's place orders before, I want to be able to see all the orders that I've placed before so that I can check it out again

**User Acceptance Criteria**
- [ ]  I can see a listt of my orders
- [ ] When I click on them I can see at minimum its title and order time. other potential things could be time of storing to database (successful retrieval and storage, aka done building?), time "delivered" (like the email was sent?)
- [ ] I should also see the image itself full size when i click on the order.
- [ ] i can easily get our of the order image/full page back to the list.
- [ ] The list of orders should have a preview of the order, not full size but a preview

**Non-Functional Requirements**
some non-functional requirements to take note of as we design the solution to the user story
- [ ] None we can think of rn

**Task List**
- [ ] get the orders from our database of the current user.
- [ ] each order has info + thumbnail that we show put into one card
- [ ] clicking on that "card" will popup/expand the order into a full size image for the user to see.
