### ISSUE TITLE
As an existing user I want to be able to delete my account so that i won't get spam emails

### ISSUE THREAD

**Issue by DatNgoNYC** [DatNgoNYC/anythingyouwantt#7]
### User Story
As an existing user I want to be able to delete my account so that i won't get spam emails

**User Acceptance Criteria**
- [ ] I can delete account in the dashboard
- [ ] I should see a warning/confirmation 
- [ ] I should understand the repercussions to my personal order data 

**Non-Functional Requirements**
some non-functional requirements to take note of as we design the solution to the user story
- [ ] if there were a data breach, there should be no record of us having that user

**Task List**
- [ ] delete record from our database
