### ISSUE TITLE
As an existing customer, I should be able to sign out

### ISSUE THREAD

**Issue by DatNgoNYC** [DatNgoNYC/anythingyouwantt#8]
### User Story
As an existing customer, I should be able to sign out

**User Acceptance Criteria**
- [ ] signout button i can click and is obvious? what does "obvious" mean, who knows.

**Non-Functional Requirements**
some non-functional requirements to take note of as we design the solution to the user story
- [ ] None we can think of rn

**Task List**
- [ ] signout button
- [ ] see integration with "sessions management". I wonder if there's some sort of overlap there.
